# Generated by Django 6.0.2 on 2026-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('score', models.CharField(blank=True, help_text='CGPA or Percentage', max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., GitHub, LinkedIn, Email', max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class or similar', max_length=100, null=True)),
            ],
        ),
    ]
