# Generated by Django 6.0.2 on 2026-03-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='AYUSH', max_length=100)),
                ('last_name', models.CharField(default='KUMAR', max_length=100)),
                ('title_prefix', models.CharField(default='A Cloud', max_length=200)),
                ('title_suffix', models.CharField(default='Developer<br>Engineer', max_length=200)),
                ('about_text', models.TextField(default='I build robust cloud architectures, dynamic web applications, and scalable backend systems using Python, Django, and AWS.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='portfolio/profile/')),
                ('github_image_url', models.URLField(blank=True, help_text='Fallback image URL (e.g., https://github.com/Ayush12708.png)', null=True)),
                ('resume_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
