# Generated by Django 6.0.2 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill_icon_class_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your actual PDF resume here to host it directly on the site.', null=True, upload_to='portfolio/resumes/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_link',
            field=models.URLField(blank=True, help_text='Use this for external links like Google Drive.', null=True),
        ),
    ]
